version: '3'
services:
    server:
        container_name: server_quiz_debag
        build:  
            context: ./
            dockerfile: ./server/Dockerfile
        command: >
            sh -c "
             python manage.py makemigrations &&
             python manage.py migrate &&
             python  manage.py loaddata main/fixtures/initial_data.json &&
             python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./server:/server
        ports:
            - 80:8000
        depends_on:
            - db
        environment:
            DEBUG: 'True'
            DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
    db:
        container_name: postgres_quiz_debag
        image: postgres:11.2
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
    redis:
        container_name: redis_quiz_debag
        image: redis:5.0.3
