# Generated by Django 3.1.3 on 2021-05-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Прогрес', 'verbose_name_plural': 'Прогрес'},
        ),
        migrations.AlterField(
            model_name='achievements',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='type',
            field=models.CharField(choices=[('Commmon', 'Commmon'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Legendary', 'Legendary')], max_length=255),
        ),
        migrations.AlterField(
            model_name='progress',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
